"""
Standalone Agent Exporter.
Packages a trained model and required inference scripts
into a single, deployable Python file that doesn't need
the ModelFactory UI to run.
"""
import logging
import shutil
import zipfile
from pathlib import Path
from typing import Callable, Optional

logger = logging.getLogger(__name__)


class StandaloneExporter:
    """Exports models to a standalone runnable package."""

    def __init__(self, model_name: str, settings_manager):
        self.model_name = model_name
        self._settings  = settings_manager

    def export(
        self,
        output_dir:  str,
        progress_cb: Optional[Callable[[str], None]] = None
    ) -> bool:
        """
        Creates a zip file containing the model and a runner script.
        """
        model_dir = Path("models") / self.model_name / "best"
        if not model_dir.exists():
            if progress_cb:
                progress_cb(f"Error: Model {self.model_name} 'best' not found.")
            return False

        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        zip_name = out_path / f"standalone_agent_{self.model_name}.zip"

        def log(msg):
            logger.info(f"Export: {msg}")
            if progress_cb:
                progress_cb(msg)

        log(f"Starting export for {self.model_name}...")

        try:
            with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zf:
                # 1. Copy model files
                log("Compressing model weights...")
                for f in model_dir.rglob("*"):
                    if f.is_file():
                        arc_name = Path("model") / f.relative_to(model_dir)
                        zf.write(f, arc_name)

                # 2. Add Runner Script
                log("Generating runner script...")
                runner_code = self._generate_runner_script()
                zf.writestr("run_agent.py", runner_code)

                # 3. Add requirements.txt
                reqs = (
                    "tensorflow==2.10.0\n"
                    "opencv-python\n"
                    "numpy\n"
                    "pyautogui\n"
                    "mss\n"
                    "keyboard\n"
                )
                zf.writestr("requirements.txt", reqs)

                # 4. Add config if exists
                config_path = Path("models") / self.model_name / "config.json"
                if config_path.exists():
                    zf.write(config_path, "config.json")

            log(f"Export complete: {zip_name}")
            return True

        except Exception as e:
            log(f"Export failed: {e}")
            return False

    def _generate_runner_script(self) -> str:
        """Generates the content of run_agent.py."""
        return f"""\"\"\"
Standalone Engine for {self.model_name}
Auto-generated by ModelFactory.

Usage:
  pip install -r requirements.txt
  python run_agent.py
\"\"\"
import os
import time
import cv2
import mss
import numpy as np
import pyautogui
import keyboard
import tensorflow as tf

MODEL_DIR = "model"
CONFIDENCE_THRESHOLD = 0.85

def load_model():
    print(f"Loading model from {{MODEL_DIR}}...")
    try:
        model = tf.keras.models.load_model(MODEL_DIR)
        print("Model loaded successfully.")
        return model
    except Exception as e:
        print(f"Failed to load model: {{e}}")
        exit(1)

def run_loop(model):
    print("Agent started. Press 'q' to stop.")
    sct = mss.mss()
    # Assuming primary monitor
    monitor = sct.monitors[1]

    while not keyboard.is_pressed('q'):
        start_time = time.time()
        
        # 1. Capture screen
        sct_img = sct.grab(monitor)
        img = np.array(sct_img)[:, :, :3] # Remove alpha
        
        # 2. Preprocess (resize to what MobileNet expects)
        img_resized = cv2.resize(img, (224, 224))
        img_rgb     = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)
        img_tensor  = tf.cast(img_rgb, tf.float32) / 255.0
        img_tensor  = tf.expand_dims(img_tensor, 0)
        
        # 3. Predict
        preds = model.predict(img_tensor, verbose=0)[0]
        # Example: assuming binary classification (action vs no-action)
        # Or you will need to map this to your specific trained outputs
        best_idx = np.argmax(preds)
        conf = preds[best_idx]
        
        if conf > CONFIDENCE_THRESHOLD:
            print(f"Action triggered! Class: {{best_idx}}, Conf: {{conf:.2f}}")
            # --- ADD YOUR AUTO-GUI CLICKS HERE ---
            # e.g., pyautogui.click()
            time.sleep(1.0) # Cooldown
            
        # Optional: Frame rate limiting
        elapsed = time.time() - start_time
        if elapsed < 0.1:
            time.sleep(0.1 - elapsed)

    print("Agent stopped safely.")

if __name__ == "__main__":
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # Hide TF warnings
    model = load_model()
    run_loop(model)
"""
